before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0

dockers:
  - image_templates:
      - "dyescape/event-indexer:latest"
      - "dyescape/event-indexer:v{{ .Major }}"
      - "dyescape/event-indexer:v{{ .Major }}.{{ .Minor }}"
      - "dyescape/event-indexer:{{ .Tag }}"
    build_flag_templates:
      - "--label=GIT_TAG={{ .Tag }}"
    dockerfile: Dockerfile.goreleaser

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
