version: '3'

services:

  indexer:
    image: dyescape/event-indexer
    build:
      context: ./
    restart: on-failure
    volumes:
      - ./.event-indexer.toml:/app/.event-indexer.toml
    depends_on:
      - kafka
      - elastic
    networks:
      - default

  publisher:
    image: dyescape/event-indexer
    build:
      context: ./
    restart: on-failure
    volumes:
      - ./.event-indexer.toml:/app/.event-indexer.toml
    depends_on:
      - kafka
      - indexer
    command: ["publish"]
    networks:
      - default

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    ports:
      - 8080:8080
    networks:
      - default

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - default

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - default

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    ports:
      - 8081:5601
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
    networks:
      - default

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    restart: always
    environment:
      - cluster.name=Dyescape
      - node.name=master
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - default

volumes:
  elastic:
    driver: local

networks:
  default:
    driver: bridge